<#
    backtest.ps1 — MT5 Strategy Tester ko bina haath lagaye chalata hai
    aur HTML report bana kar uska raasta bata deta hai.

    Misaal:
        .\tools\backtest.ps1 -Expert TrendMomentumEA
        .\tools\backtest.ps1 -Expert TrendMomentumEA -Symbol XAUUSD -Period M5 `
                             -From 2025.01.01 -To 2026.08.29 -Deposit 10000
#>
param(
    [Parameter(Mandatory=$true)]
    [string]$Expert,                       # MQL5\Experts ke andar ka naam, .ex5 ke baghair
    [string]$Symbol   = "XAUUSD",
    [string]$Period   = "M5",              # M1 M5 M15 M30 H1 H4 D1
    [string]$From     = "2025.01.01",
    [string]$To       = "",                # khali = aaj tak
    [int]   $Deposit  = 10000,
    [string]$Currency = "USD",
    [string]$Leverage = "1:100",
    [int]   $Model    = 1,                 # 0=every tick 1=1-min OHLC 2=open prices 4=real ticks
    [string]$Terminal = "",                # khali = khud dhoondh lega
    [string]$Inputs   = ""                 # "InpSL_Points=500||InpTP_Points=750"
)

$ErrorActionPreference = "Stop"

function Find-Terminal {
    if ($env:MT5_TERMINAL -and (Test-Path $env:MT5_TERMINAL)) { return $env:MT5_TERMINAL }
    $candidates = @(
        "C:\Program Files\MetaTrader 5\terminal64.exe",
        "C:\Program Files (x86)\MetaTrader 5\terminal64.exe"
    )
    foreach ($c in $candidates) { if (Test-Path $c) { return $c } }
    foreach ($root in @("C:\Program Files", "C:\Program Files (x86)")) {
        if (Test-Path $root) {
            $hit = Get-ChildItem -Path $root -Filter "terminal64.exe" -Recurse -ErrorAction SilentlyContinue |
                   Select-Object -First 1
            if ($hit) { return $hit.FullName }
        }
    }
    return $null
}

if (-not $Terminal) { $Terminal = Find-Terminal }
if (-not $Terminal) {
    Write-Host "terminal64.exe nahi mila. Raasta khud dein: -Terminal ""C:\...\terminal64.exe""" -ForegroundColor Red
    exit 2
}
if (-not $To) { $To = (Get-Date).ToString("yyyy.MM.dd") }

$outDir = Join-Path (Get-Location) "backtest"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$stamp      = Get-Date -Format "yyyyMMdd-HHmmss"
$reportBase = Join-Path $outDir "$Expert-$Symbol-$Period-$stamp"
$iniPath    = "$reportBase.ini"

$ini = @"
; Auto-generated by tools\backtest.ps1 — ise haath se edit karne ki zaroorat nahi
[Tester]
Expert=$Expert
Symbol=$Symbol
Period=$Period
Optimization=0
Model=$Model
FromDate=$From
ToDate=$To
ForwardMode=0
Deposit=$Deposit
Currency=$Currency
Leverage=$Leverage
ExecutionMode=0
Visual=0
Report=$reportBase
ReplaceReport=1
ShutdownTerminal=1
"@

if ($Inputs) {
    $ini += "`r`n[TesterInputs]`r`n"
    foreach ($pair in $Inputs.Split("||", [StringSplitOptions]::RemoveEmptyEntries)) {
        if ($pair.Trim()) { $ini += ($pair.Trim() + "`r`n") }
    }
}

Set-Content -Path $iniPath -Value $ini -Encoding ASCII

Write-Host "Terminal : $Terminal"       -ForegroundColor DarkGray
Write-Host "Expert   : $Expert"         -ForegroundColor DarkGray
Write-Host "Symbol   : $Symbol $Period" -ForegroundColor DarkGray
Write-Host "Range    : $From -> $To"    -ForegroundColor DarkGray
Write-Host ""
Write-Host "Backtest chal raha hai... (pehli dafa history download hone mein waqt lag sakta hai)" -ForegroundColor Cyan

Start-Process -FilePath $Terminal -ArgumentList "/config:`"$iniPath`"" -Wait -NoNewWindow

$report = Get-ChildItem -Path $outDir -Filter "$(Split-Path $reportBase -Leaf)*.htm*" -ErrorAction SilentlyContinue |
          Select-Object -First 1

if ($report) {
    Write-Host ""
    Write-Host "Report ban gayi:" -ForegroundColor Green
    Write-Host "  $($report.FullName)"
    Write-Host ""
    Write-Host "Ise Claude ko parhne ke liye kahein — wo numbers nikaal kar bata dega." -ForegroundColor DarkGray
    exit 0
}

Write-Host ""
Write-Host "Report nahi bani. Aam wajuhat:" -ForegroundColor Red
Write-Host "  - EA compile nahi hua (pehle tools\compile.bat chalayen)"
Write-Host "  - $Expert.ex5 MQL5\Experts folder mein maujood nahi"
Write-Host "  - $Symbol Market Watch mein nahi, ya us ki history nahi hai"
Write-Host "  - Terminal pehle se khula tha (band kar ke dobara chalayen)"
Write-Host "Ini file: $iniPath"
exit 1
